{"name": "test_login_success", "status": "passed", "description": "This test successfully authorizes a user by email and password", "start": 1709476780634, "stop": 1709476781929, "uuid": "93c65f11-0f57-4bcb-b6e7-8b1a7b7661d0", "historyId": "86600b41e86dab7ca99f472fa61e4b05", "testCaseId": "86600b41e86dab7ca99f472fa61e4b05", "fullName": "tests.test_login#test_login_success", "labels": [{"name": "severity", "value": "critical"}, {"name": "feature", "value": "Login Feature"}, {"name": "story", "value": "Successful authentication"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "fv-az1390-687"}, {"name": "thread", "value": "1488-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}], "links": [{"type": "tms", "url": "TC-1", "name": "http://test-case/TC-1"}, {"type": "issue", "url": "AUTH-1", "name": "http://issue-tracker/AUTH-1"}]}